name = "DrWatsonHelpers"
uuid = "7fdc9ab4-4ff2-4741-8c67-1b227ee32b66"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de>"]
version = "0.1.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
